name: ci
on: { push: { branches: [ main ] } }
jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{ github.actor }}, password: ${{ secrets.GITHUB_TOKEN }} }
      - name: Build & Push images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ingest:${{ github.sha }} apps/ingest
          docker build -t ghcr.io/${{ github.repository }}/transform:${{ github.sha }} apps/transform
          docker build -t ghcr.io/${{ github.repository }}/api:${{ github.sha }} apps/api
          docker push ghcr.io/${{ github.repository }}/ingest:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/transform:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/api:${{ github.sha }}
      - uses: azure/setup-kubectl@v4
      - name: Configure kubeconfig
        run: echo "${KUBECONFIG_B64}" | base64 -d > kubeconfig.yml
        env: { KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }} }
      - name: Deploy (kustomize)
        env: { KUBECONFIG: ${{ github.workspace }}/kubeconfig.yml }
        run: kubectl apply -k deploy/k8s/overlays/dev
